# Generated by Django 5.1.5 on 2025-01-25 20:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
