# Generated by Django 5.1.5 on 2025-01-26 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0004_alter_onetimepassword_token'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OneTimePassword',
        ),
    ]
