# Generated by Django 5.1.5 on 2025-02-05 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='updated',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='status',
            field=models.CharField(choices=[('EXP', 'منقضی شده'), ('ACT', 'فعال')], default='ACT', max_length=3, verbose_name='وضعیت'),
        ),
    ]
