# Generated by Django 5.1.5 on 2025-01-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesocialmedia',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='github_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gitlab_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='instagram_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='x_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='youtube_profile',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProfileSecurityAuthentication',
        ),
        migrations.DeleteModel(
            name='ProfileSocialMedia',
        ),
    ]
