# Generated by Django 5.1.5 on 2025-02-06 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0002_alter_tasks_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
